In [1]:
import pandas as pd

In [3]:
pd.read_pickle('../results/fluxos_DG_California.pkl')

,data,target
Anaheim,"[0.0, 34907.0, 0.0, 390.0, 0.0, 175.0, 68.0, 5...","[2.349846, 9105.421, 554.5301, 665.6176, 0.060..."
Cypress,"[45.0, 1769.0, 0.0, 0.0, 185.0, 600.0, 269.0, ...","[950.8942, 1530.4738, 1.2200515, 0.44610712, 1..."
Orange,"[75.0, 86.0, 9798.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[716.3252, 1023.852, 2741.8467, 0.15525976, 0...."
San Juan Capistrano,"[0.0, 0.0, 218.0, 0.0, 0.0, 0.0, 5645.0, 0.0, ...","[147.50635, 49.123764, 2926.004, 0.012499129, ..."
Santa Ana,"[47.0, 101.0, 0.0, 147.0, 0.0, 410.0, 104.0, 0...","[483.9388, 1034.2874, 7.782104, 2396.922, 0.57..."
...,...,...
West Carson,"[0.0, 0.0, 0.0, 58.0, 0.0, 365.0, 0.0, 0.0, 0....","[0.68564963, 271.04837, 181.08784, 530.9843, 1..."
Westmont,"[0.0, 116.0, 0.0, 0.0, 0.0, 200.0, 55.0, 0.0, ...","[115.849915, 737.4114, 1.0283498, 96.11582, 20..."
West Puente Valley,"[0.0, 0.0, 0.0, 125.0, 0.0, 0.0, 0.0, 562.0, 0...","[0.30310905, 0.52575725, 0.30931672, 574.14844..."
Winter Gardens,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.7040987, 2.3469932, 51.968567, 0.0031362926..."
Yosemite Lakes,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.27958146, 64.953735, 20.406725, 5.0640297, ..."